<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="$(ProductionSource)" Link="DeckMenuControls.cs" />
    <Compile Include="$(ProductionButton)" Link="CustomButton.cs" />
  </ItemGroup>
</Project>
